INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(    1, "Never say never", 1, 1, 90);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(    2, "ドラマ「目指せ!シンデレラNO.1! -渋谷凛編-」", 1, 2, 65534);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(    3, "Never say never (オリジナル・カラオケ)", 1, 3, 90);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(    4, "ボーナス・トラック", 1, 4, 65535);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(    5, "あんずのうた", 2, 1, 178);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(    6, "ドラマ「目指せ!シンデレラNO.1! -双葉杏編-」", 2, 2, 65534);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(    7, "あんずのうた (オリジナル・カラオケ)", 2, 3, 178);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(    8, "ボーナス・トラック", 2, 4, 65535);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(    9, "ショコラ・ティアラ", 3, 1, 254);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   10, "ドラマ「目指せ!シンデレラNO.1! -三村かな子編-」", 3, 2, 65534);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   11, "ショコラ・ティアラ (オリジナル・カラオケ)", 3, 3, 254);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   12, "ボーナス・トラック", 3, 4, 65535);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   13, "こいかぜ", 4, 1, 193);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   14, "ドラマ「目指せ!シンデレラNO.1! -高垣楓編-」", 4, 2, 65534);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   15, "こいかぜ (オリジナル・カラオケ)", 4, 3, 193);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   16, "ボーナス・トラック", 4, 4, 65535);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   17, "DOKIDOKIリズム", 5, 1, 23);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   18, "ドラマ「目指せ!シンデレラNO.1! -城ヶ崎莉嘉編-」", 5, 2, 65534);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   19, "DOKIDOKIリズム (オリジナル・カラオケ)", 5, 3, 23);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   20, "ボーナス・トラック", 5, 4, 65535);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   21, "華蕾夢ミル狂詩曲〜魂ノ導〜", 6, 1, 405);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   22, "ドラマ「目指せ!シンデレラNO.1! -神崎蘭子編-」", 6, 2, 65534);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   23, "ドラマ「目指せ!シンデレラNO.1! -神崎蘭子編-」(副音声付きver.)", 6, 3, 65534);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   24, "華蕾夢ミル狂詩曲〜魂ノ導〜 (オリジナル・カラオケ)", 6, 4, 405);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   25, "ボーナス・トラック", 6, 5, 65535);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   26, "おねだり Shall We 〜?", 7, 1, 183);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   27, "ドラマ「目指せ!シンデレラNO.1! -前川みく編-」", 7, 2, 65534);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   28, "おねだり Shall We 〜? (オリジナル・カラオケ)", 7, 3, 183);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   29, "ボーナス・トラック", 7, 4, 65535);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   30, "ましゅまろ☆キッス", 8, 1, 216);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   31, "ドラマ「目指せ!シンデレラNO.1! -諸星きらり編-」", 8, 2, 65534);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   32, "ましゅまろ☆キッス (オリジナル・カラオケ)", 8, 3, 216);
INSERT INTO `cinderella`.`tracks`(`id`, `name`, `disc`, `track`, `music`) VALUES(   33, "ボーナス・トラック", 8, 4, 65535);
