insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 16, "Butter-Fly", "ばたふらい", "千綿偉功", "千綿偉功", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 17, "COLORS", "からーず", "KOHSHI ASAKAWA, KEIGO HAYASHI", "KOHSHI ASAKAWA", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 18, "CRAZY GONNA CRAZY", "くれいじーごなくれいじー", "小室哲哉", "小室哲哉", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 22, "Connecting Happy!!", "こねくてぃんぐはっぴー", "畑亜貴", "高尾奏之介(F.M.F)", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 33, "EZ DO DANCE", "いーじーどぅだんす", "小室哲哉", "小室哲哉", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 43, "God knows...", "ごっどのうず", "畑亜貴", "神前暁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 47, "HIGH PRESSURE", "はいぷれっしゃー", "井上秋緒", "浅倉大介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 48, "HOT LIMIT", "ほっとりみっと", "井上秋緒", "浅倉大介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 49, "Hacking to the Gate", "はっきんぐとぅざげーと", "志倉千代丸", "志倉千代丸", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 54, "Hello Especially", "はろーえすぺしゃりー", "スキマスイッチ", "スキマスイッチ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 58, "I wish", "あいうぃっしゅ", "三浦徳子", "白川善久", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 62, "KISSして", "きすして", "福山雅治", "福山雅治", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 65, "LIFE", "らいふ", "山内総一郎", "山内総一郎", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 66, "LOVE & PEACH", "らぶあんどぴーち", "北川悠仁", "北川悠仁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 68, "LOVE & JOY", "らぶあんどじょい", "麻倉真琴", "浅倉大介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 73, "Lost Princess", "ろすとぷりんせす", "しほり", "田中公平", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 74, "Lost my music", "ろすとまいみゅーじっく", "畑亜貴", "神前暁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 81, "My Soul, Your Beats!", "まいそうるゆあびーつ", "麻枝准", "麻枝准", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 95, "O2", "おーつー", "ORANGE RANGE", "ORANGE RANGE", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 97, "OVER THE SKY", "おーばーざすかい", "Narucho", "植松伸夫, Johnny.k", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(101, "Overnight Sensation ～時代はあなたに委ねてる～", "おーばーないとせんせーしょんじだいはあなたにゆだねてる", "小室哲哉", "小室哲哉", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(104, "PURE SNOW", "ぴゅあすのー", "佐々木ゆう子", "木根尚登", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(107, "Perseus-ペルセウス-", "ぺるせうす", "BOUNCEBACK", "迫茂樹", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(110, "RAGE OF DUST", "れいじおぶだすと", "MOMIKEN", "UZ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(111, "REVENGE", "りべんじ", "古屋真", "浅利進吾", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(114, "Reset", "りせっと", "TAK, BABY", "JUN", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(118, "STAR", "すたー", "竹平太", "Ko-ta, Ko-hey", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(153, "WHITE BREATH", "ほわいとぶれす", "井上秋緒", "浅倉大介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(159, "YELLOW YELLOW HAPPY", "いえろーいえろーはっぴー", "CHIAKI, ポケットビスケッツ", "パッパラー河合", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(163, "brave heart", "ぶれいぶはーと", "大森祥子", "太田美知彦", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(170, "survival dAnce ～no no cry more～", "さばいばるだんすのーのーくらいもあ", "小室哲哉", "小室哲哉", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(179, "いつかの、いくつかのきみとのせかい", "いつかのいくつかのきみとのせかい", "林英樹", "佐藤純一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(189, "きみにとどけ", "きみにとどけ", "タニザワトモフミ", "タニザワトモフミ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(194, "ここにしか咲かない花", "ここにしかさかないはな", "小渕健太郎", "小渕健太郎", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(198, "しっぽのきもち", "しっぽのきもち", "谷山浩子", "谷山浩子", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(200, "じょいふる", "じょいふる", "水野良樹", "水野良樹", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(210, "にんげんっていいな", "にんげんっていいな", "山口あかり", "小林亜星", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(211, "はじめてのチュウ", "はじめてのちゅう", "実川俊晴", "実川俊晴", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(217, "また君に恋してる", "またきみにあいしてる", "松井五郎", "森正明", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(225, "アルカテイル", "あるかている", "魁", "折戸伸治", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(229, "ウルトラリラックス", "うるとらりらっくす", "石野卓球", "石野卓球", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(230, "エキストラレボリューション", "えきすとられぼりゅーしょん", "ZAQ", "ZAQ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(232, "エンジェル ドリーム", "えんじょるどりーむ", "たかみつようこ", "岡部啓一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(239, "ガッツだぜ！！", "がっつだぜ", "トータス松本", "トータス松本", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(242, "キミとボクのミライ", "きみとぼくとみらい", "maimie", "植松伸夫, 成田勤", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(252, "サヨナラバス", "さよならばす", "北川悠仁", "北川悠仁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(255, "スカイクラッドの観測者", "すかいくらっどのかんそくしゃ", "志倉千代丸", "志倉千代丸", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(257, "スターラブレイション", "すたーらぶれいしょん", "ふるっぺ, 森さん, Litz", "ふるっぺ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(264, "タッタ", "たった", "北川悠仁", "北川悠仁, JIN", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(268, "ツバサ", "つばさ", "真戸原直人", "真戸原直人", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(274, "ナンダカンダ", "なんだかんだ", "GAKU-MC", "浅倉大介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(278, "ハミングがきこえる", "はみんぐがきこえる", "さくらももこ", "小山田圭吾", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(279, "ハレ晴レユカイ", "はれはれゆかい", "畑亜貴", "田代智一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(296, "メトロポリタン美術館", "めとろぽりたんびじゅつかん", "大貫妙子", "大貫妙子", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(299, "モザイクカケラ", "もざいくかけら", "石田順三", "石田順三", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(303, "ラブリー", "らぶりー", "小沢健二", "小沢健二", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(307, "リバイブ", "りばいぶ", "Kanata Okajima, Daisuke Nakamura, YUTA(UNIONE)", "Daisuke Nakamura", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(308, "ルル", "るる", "ティカ・α", "ティカ・α", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(313, "不思議なピーチパイ", "ふしぎなぴーちぱい", "安井かずみ", "加藤和彦", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(315, "亜麻色の髪の乙女", "あまいろのかみのおとめ", "橋本淳", "すぎやまこういち", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(316, "全力☆Summer!", "ぜんりょくさまー", "atsuko", "atsuko, KATSU", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(318, "冒険でしょでしょ？", "ぼうけんでしょでしょ", "畑亜貴", "冨田暁子", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(323, "友達の唄", "ともだちのうた", "北川悠仁", "北川悠仁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(327, "君の知らない物語", "きみのしらないものがたり", "ryo", "ryo", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(328, "君の青春は輝いているか", "きみのせいしゅんはかがやいているか", "ジェームス三木", "三木たかし", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(334, "夏色", "なついろ", "北川悠仁", "北川悠仁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(339, "大きな古時計", "おおきなふるどけい", "保富康午", "WORK HENRY CLAY", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(340, "大河よ共に泣いてくれ", "たいがよともにないてくれ", "古屋真", "加藤裕介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(341, "大都会交響楽", "だいとかいこうきょうきょく", "小西康陽", "小西康陽", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(344, "奏 (かなで)", "かなで", "スキマスイッチ", "スキマスイッチ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(345, "女の子は誰でも", "おんなのこはだれでも", "椎名林檎", "椎名林檎", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(346, "学園天国", "がくえんてんごく", "阿久悠", "井上忠夫", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(347, "守ってあげたい", "まもってあげたい", "松任谷由実", "松任谷由実", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(354, "徒花ネクロマンシー", "あだばなねくろまんしー", "古屋真", "加藤裕介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(360, "悲しみをやさしさに", "かなしみをやさしさに", "tetsuhiko", "tetsuhiko, Tomoji Sogawa", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(363, "愛は元気です。", "あいはげんきです", "戸沢暢美", "谷村有美", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(365, "日曜日はダメダメよ", "にちようびはだめだめよ", "小西康陽", "小西康陽", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(369, "時を刻む唄", "ときをきざむうた", "麻枝准", "麻枝准", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(370, "月のしずく", "つきのしずく", "Satomi", "松本良喜", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(372, "♡桃色片想い♡", "ももいろかたおもい", "つんく", "つんく", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(377, "気まぐれロマンティック", "きまぐれろまんてぃっく", "水野良樹", "水野良樹", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(378, "気分爽快", "きぶんそうかい", "森高千里", "黒沢健一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(388, "碧いうさぎ", "あおいうさぎ", "牧穂エミ", "織田哲郎", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(397, "紅", "くれない", "YOSHIKI", "YOSHIKI", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(406, "蒼穹", "そうきゅう", "atsuko", "atsuko, KATSU", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(409, "虹", "にじ", "北川悠仁", "北川悠仁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(410, "蛍火", "ほたるび", "須藤まゆみ", "椎名豪", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(411, "行くぜっ！怪盗少女", "いくぜっかいとうしょうじょ", "前山田健一", "前山田健一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(412, "見上げてごらん夜の星を", "みあげてごらんよるのほしを", "永六輔", "いずみたく", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(413, "誰より好きなのに", "だれよりもすきなのに", "古内東子", "古内東子", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(420, "遠く遠く", "とおくとおく", "槇原敬之", "槇原敬之", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(423, "離れていても", "はなれていても", "岡本真夜", "岡本真夜", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(424, "雪の華", "ゆきのはな", "Satomi", "松本良喜", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(428, "風になりたい", "かぜになりたい", "宮沢和史", "宮沢和史", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(430, "鳥の詩", "とりのうた", "麻枝准", "折戸伸治", 1, 0);
