insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(  1, "#HE4DSHOT", "へっどしょっと", "烏屋茶房", "橘亮祐, 篠崎あやと, 烏屋茶房", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(  2, "-LEGNE- 仇なす剣 光の旋律", "えんげるあだなすつるぎひかりのしらべ", "東ノ獄彩", "隠田遼平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(  3, "14平米にスーベニア", "じゅうよんへいべいにすうべにあ", "八城雄太", "emon", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(  4, "17才", "じゅうななさい", "有馬三恵子", "筒美京平", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(  5, "2nd SIDE", "せかんどさいど", "ESTi", "Sanch", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(  6, "Absolute NIne", "あぶそりゅーとないん", "hisakuni", "hisakuni", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(  7, "AnemoneStar", "あねもねすたー", "yasushi", "yasushi", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(  8, "Angel Breeze", "えんじぇるぶりーず", "高瀬愛虹", "百引一", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(  9, "Athanasia", "あたなしあ", "DJ'TEKINA//SOMETHING a.k.a. ゆよゆっぺ", "DJ'TEKINA//SOMETHING a.k.a. ゆよゆっぺ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 10, "BEYOND THE STARLIGHT", "びよんどざすたーらいと", "八城雄太", "石濱翔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 11, "Blessing", "ぶれっしんぐ", "貝田由里子", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 12, "Bloody Festa", "ぶらっでぃふぇすた", "ミズノゲンキ", "夏美", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 13, "Blooming Days", "ぶるーみんぐでいず", "eNu", "川田瑠夏", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 14, "Brand new!", "ぶらんどにゅー", "烏屋茶房", "烏屋茶房, 篠崎あやと, 橘亮祐", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 15, "Bright Blue", "ぶらいとぶるー", "marhy", "kyo", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 16, "Butter-Fly", "ばたふらい", "千綿偉功", "千綿偉功", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 17, "COLORS", "からーず", "KOHSHI ASAKAWA, KEIGO HAYASHI", "TAKESHI ASAKAWA", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 18, "CRAZY GONNA CRAZY", "くれいじーごなくれいじー", "小室哲哉", "小室哲哉", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 19, "Can't Stop!!", "きゃんとすとっぷ", "磯谷佳江", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 20, "Claw My Heart", "くろうまいはーと", "ミズノゲンキ", "石濱翔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 21, "CoCo夏夏夏 Holiday", "ここなつなつなつほりでー", "Funta3", "Funta7", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 22, "Connecting Happy!!", "こねくてぃんぐはっぴー", "畑亜貴", "高尾奏之介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 23, "DOKIDOKIリズム", "どきどきりずむ", "佐藤貴文", "佐藤貴文", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 24, "Dear My Dreamers", "でぃあまいどりーまーず", "八城雄太", "渡部チェル", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 25, "Demolish", "でもりっしゅ", "只野菜摘", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 26, "Drastic Melody", "どらすてぃっくめろでぃ", "R・O・N", "R・O・N", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 27, "Dreaming Star", "どりーみんぐすたー", "emon, おもち花", "emon", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 28, "Dreaming of you", "どりーみんぐおぶゆー", "mft", "広川恵一", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 29, "Driving My Way", "どらいびんぐまいうぇい", "AJURIKA", "山本真央樹", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 30, "EVERLASTING", "えばーらすてぃんぐ", "森由里子", "田中秀和, 滝澤俊輔, 睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 31, "EVERMORE", "えばーもあー", "森由里子", "田中秀和, 滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 32, "EVIL LIVE", "いーびるらいぶ", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 33, "EZ DO DANCE", "いーじーどぅだんす", "小室哲哉", "小室哲哉", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 34, "FLY ME TO THE MOON", "ふらいみーとぅざむーん", "Bart Howard", "Bart Howard", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 35, "Fascinate", "ふぁっしねいと", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 36, "Flip Flop", "ふりっぷふろっぷ", "ミト", "ミト", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 37, "Frost", "ふろすと", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 38, "Frozen Tears", "ふろーずんてぃあーず", "磯谷佳江", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 39, "GEMSTONE", "じぇむすとーん", "出口遼", "出口遼", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 40, "GOIN'!!!", "ごーいん", "森由里子", "宮崎まゆ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 41, "Gaze and Gaze", "げいずあんどげいず", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 42, "Go Just Go!", "ごーじゃすとごー", "八城雄太", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 43, "God knows...", "ごっどのうず", "畑亜貴", "神前暁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 44, "Gossip Club", "ごしっぷくらぶ", "俊龍", "Sizuk", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 45, "Great Journey", "ぐれーとじゃーにー", "磯谷佳江", "内田哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 46, "HARURUNRUN", "はるらんらん", "田村歩美", "田村歩美", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 47, "HIGH PRESSURE", "はいぷれっしゃー", "井上秋緒", "浅倉大介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 48, "HOT LIMIT", "ほっとりみっと", "井上秋緒", "浅倉大介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 49, "Hacking to the Gate", "はっきんぐとぅざげーと", "志倉千代丸", "志倉千代丸", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 50, "Halloween♥Code", "はろうぃーんこーど", "磯谷佳江", "岡野裕次郎", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 51, "Happy New Yeah!", "はっぴーにゅーいぇー", "八城雄太", "高取ヒデアキ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 52, "Happy×2 Days", "はっぴーはっぴーでいず", "木村有希", "岡野裕次郎", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 53, "Heart Voice", "はーとぼいす", "磯谷佳江", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 54, "Hello Especially", "はろーえすぺしゃりー", "スキマスイッチ", "スキマスイッチ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 55, "Home Sweet Home", "ほーむすいーとほーむ", "八城雄太", "Powerless", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 56, "Hotel Moonside", "ほてるむーんさいど", "MC TC", "Taku Inoue", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 57, "Hungry Bambi", "はんぐりーばんび", "出口遼", "出口遼", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 58, "I wish", "あいうぃっしゅ", "三浦徳子", "白川善久", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 59, "Jet to the Future", "じぇっととぅざふゅーちゃー", "磯谷佳江", "IMAJO", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 60, "Joker", "じょーかー", "渡部紫緒", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 61, "Just Us Justice", "じゃすとあすじゃすてぃす", "ミズノゲンキ", "ゆよゆっぺ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 62, "KISSして", "きすして", "福山雅治", "福山雅治", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 63, "Kawaii make MY day!", "かわいいめいくまいでい", "八城雄太", "石濱翔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 64, "LET'S GO HAPPY!!", "れっつごーはっぴー", "夕野ヨシミ", "ARM", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 65, "LIFE", "らいふ", "山内総一郎", "山内総一郎", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 66, "LOVE & PEACH", "らぶあんどぴーち", "北川悠仁", "北川悠仁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 67, "LOVE 2000", "らぶにせん", "hitomi", "鎌田雅人", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 68, "LOVE&JOY", "らぶあんどじょい", "麻倉真琴", "浅倉大介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 69, "LOVE☆ハズカム", "らぶはずかむ", "磯谷佳江", "山本真央樹", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 70, "Last Kiss", "らすときす", "渡部紫緒", "坂部剛", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 71, "Let's Sail Away!!!", "れっつごーあうぇい", "坂井竜二", "アオワイファイ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 72, "Life is HaRMONY", "らいふいずはーもにー", "no_my", "no_my", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 73, "Lost Princess", "ろすとぷりんせす", "しほり", "田中公平", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 74, "Lost my music", "ろすとまいみゅーじっく", "畑亜貴", "神前暁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 75, "Love∞Destiny", "らぶでぃすてぃにー", "磯谷佳江", "kyo", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 76, "Lunatic Show", "るなてぃっくしょー", "磯谷佳江", "IMAJO", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 77, "M@GIC☆", "まじっく", "森由里子", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 78, "Max Beat", "まっくすびーと", "渡部紫緒", "坂部剛", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 79, "Memories", "めもりーず", "貝田由里子", "ESTi", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 80, "Milky Mode", "みるきーもーど", "YASUHIRO(康寛)", "", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 81, "My Soul, Your Beats!", "まいそうるゆあびーつ", "麻枝准", "麻枝准", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 82, "Myself", "まいせるふ", "馬渕直純", "馬渕直純", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 83, "NUDIE★", "ぬーでぃー", "小金井つくも", "TAKT", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 84, "Naked Romance", "ねいきっどろまんす", "遠山明孝", "遠山明孝", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 85, "Nation Blue", "ねいしょんぶるー", "遠山明孝", "遠山明孝", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 86, "Near to You", "にあとぅゆー", "AJURIKA", "AJURIKA", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 87, "Nebula Sky", "ねびゅらすかい", "AJURIKA", "AJURIKA", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 88, "Needle Light", "にーどるらいと", "AJURIKA", "AJURIKA", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 89, "Neo Beautiful Pain", "ねおびゅーてぃふるぺいん", "AJURIKA", "AJURIKA", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 90, "Never Say Never", "ねばーせいねばー", "八城雄太, 遠山明孝", "遠山明孝", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 91, "Never ends", "ねばーえんず", "渡部紫緒", "ESTi", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 92, "Nocturne", "のくたーん", "AJURIKA", "AJURIKA", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 93, "Nothing but You", "なっしんぐばっとゆー", "AJURIKA", "AJURIKA", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 94, "O-Ku-Ri-Mo-No Sunday!", "おくりものさんでー", "烏屋茶房", "烏屋茶房, 篠崎あやと", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 95, "O2", "おーつー", "ORANGE RANGE", "ORANGE RANGE", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 96, "OTAHEN アンセム", "おたへんあんせむ", "佐藤貴文", "佐藤貴文", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 97, "OVER THE SKY", "おーばーざすかい", "Narucho", "植松伸夫, Johnny.k", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 98, "One Life", "わんらいふ", "ミズノゲンキ", "根本優樹", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values( 99, "Orange Sapphire", "おれんじさふぁいあ", "Funta3", "Funta7", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(100, "Over Drive", "おーばーどらいぶ", "YUKI", "TAKUYA", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(101, "Overnight Sensation ～時代はあなたに委ねてる～", "おーばーないとせんせーしょんじだいはあなたにゆだねてる", "小室哲哉", "小室哲哉", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(102, "PANDEMIC ALONE", "ぱんでみっくあろーん", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(103, "PROUST EFFECT", "ぷるーすとえふぇくと", "北谷光浩", "北谷光浩", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(104, "PURE SNOW", "ぴゅあすのー", "佐々木ゆう子", "木根尚登", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(105, "Packing Her Favorite", "ぱっきんぐはーふぇいばりっと", "八城雄太", "seibin", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(106, "Palette", "ぱれっと", "桜アス恵", "seibin", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(107, "Perseus-ペルセウス-", "ぺるせうす", "BOUNCEBACK", "迫茂樹", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(108, "Pretty Liar", "ぷりてぃらいあー", "森由里子", "石濱翔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(109, "Private Sign", "ぷらいべーとさいん", "Apis", "内海孝彰", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(110, "RAGE OF DUST", "れいじおぶだすと", "MOMIKEN", "UZ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(111, "REVENGE", "りべんじ", "古屋真", "浅利進吾", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(112, "Radio Happy", "れでぃおはっぴー", "MC TC", "Taku Inoue", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(113, "Reflective illumination night", "りふれくてぃぶいるみねーしょんないと", "baker", "篠崎あやと", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(114, "Reset", "りせっと", "TAK, BABY", "JUN", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(115, "Rockin' Emotion", "ろっきんえもーしょん", "磯谷佳江", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(116, "Romantic Now", "ろまんてぃっくなう", "MC TC", "Taku Inoue", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(117, "S(mile)ING!", "すまいりんぐ", "八城雄太", "Yoshi", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(118, "STAR", "すたー", "竹平太", "Ko-ta, Ko-hey", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(119, "STORY", "すとーりー", "森由里子", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(120, "SUN♡FLOWER", "さんふらわー", "坂井竜二", "山崎真吾", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(121, "SUPERLOVE☆", "すーぱーらぶ", "小金井つくも", "内田哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(122, "Secret Daybreak", "しーくれっとでいぶれいく", "烏屋茶房", "烏屋茶房", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(123, "Secret Mirage", "しーくれっとみらーじゅ", "磯谷佳江", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(124, "Shine!!", "しゃいん", "森由里子", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(125, "Shinobi 4.0 忍者のすゝめ", "しのびよんてんぜろにんじゃのすすめ", "八城雄太", "高取ヒデアキ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(126, "Sing the Prologue♪", "しんぐざぷろろーぐ", "高瀬愛虹", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(127, "Snow Wings", "すのーうぃんぐ", "俊龍", "俊龍", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(128, "Snow＊Love", "すのーらぶ", "ヒゲドライバー", "ヒゲドライバー", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(129, "Sparkling Girl", "すぱーきんぐがーるず", "磯谷佳江", "細見卓也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(130, "Spring Screaming", "すぷりんぐすくりーみんぐ", "宮崎誠", "宮崎誠", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(131, "Stage Bye Stage", "すてーじばいすてーじ", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(132, "Star!!", "すたー", "森由里子", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(133, "Starry-Go-Round", "すたーりーごーらんど", "磯谷佳江", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(134, "Sunshine See May", "さんしゃいんしーめい", "只野菜摘", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(135, "Sun！High！Gold！", "さんはいごーるど", "八城雄太", "高取ヒデアキ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(136, "Sweet Witches' Night ～6人目はだぁれ～", "すいーとうぃっちーずろくにんめはだぁれ", "角本麻衣", "角本麻衣", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(137, "TAKAMARI☆CLIMAXXX!!!!!", "たかまりくらいまっくす", "広川恵一", "広川恵一", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(138, "THE VILLAIN'S NIGHT", "ざびらんずないと", "坂井竜二", "TAKT", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(139, "TOKIMEKIエスカレート", "すきめきえすかれーと", "marhy", "内田哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(140, "TRUE COLORS", "とぅるーからーず", "渡辺量", "", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(141, "Take me☆Take you", "ていくみーていくゆー", "渡部紫緒", "坂部剛", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(142, "To my darling...", "とぅまいだーりん", "Mitsu", "平井克明", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(143, "Trancing Pulse", "とらんしんぐぱるす", "AJURIKA", "上松範康", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(144, "Treasure☆", "とれじゃー", "デレパジ", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(145, "Trinity Field", "とりにてぃふぃーるど", "奥井雅美", "上松範康", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(146, "Trust me", "とらすとみー", "ゆよゆっぺ", "ゆよゆっぺ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(147, "Tulip", "ちゅーりっぷ", "森由里子", "石濱翔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(148, "Twilight Sky", "とわいらいとすかい", "渡辺量", "後藤貴徳", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(149, "Twin☆くるっ★テール", "ついんくるってーる", "八城雄太", "内海孝彰", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(150, "Unlock Starbeat", "あんろっくすたーびーと", "磯谷佳江", "IMAJO", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(151, "Vast world", "ばすとわーるど", "eNu", "設楽哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(152, "Voyage", "ぼやーじゅ", "烏屋茶房", "井上馨太", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(153, "WHITE BREATH", "ほわいとぶれす", "井上秋緒", "浅倉大介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(154, "We're the friends!", "うぃーあーふれんず", "森由里子", "藤末樹", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(155, "White again", "ほわいとあげいん", "eNu", "橋本由香利", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(156, "Wish you Happiness!!", "うぃっしゅゆーはびねす", "宮崎誠", "宮崎誠", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(157, "With Love", "うぃずらぶ", "絵伊子", "渡部チェル", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(158, "Wonder goes on!!", "わんだーごーずおん", "磯谷佳江", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(159, "YELLOW YELLOW HAPPY", "いえろーいえろーはっぴー", "CHIAKI&ポケットビスケッツ", "パッパラー河合", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(160, "Yes! Party Time!!", "いえすぱーてぃーたいむ", "俊龍", "Sizuk", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(161, "You're stars shine on me", "ゆーあーすたーずしゃいんおんみー", "貝田由里子", "小林啓樹", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(162, "always", "おーるうぇいず", "藤田麻衣子", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(163, "brave heart", "ぶれいぶはーと", "大森祥子", "太田美知彦", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(164, "cherry＊merry＊cherry", "ちぇりーめりーちぇりー", "坂井竜二", "山崎真吾", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(165, "comic cosmic", "こみっくこずみっく", "只野菜摘", "篠崎あやと, 橘亮祐", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(166, "if", "いふ", "藤田麻衣子", "藤田麻衣子", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(167, "in fact", "いんふぁくと", "Maiko Fujita", "Maiko Fujita", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(168, "lilac time", "らいらっくたいむ", "橋本由香利", "橋本由香利", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(169, "shabon song", "しゃぼんそんぐ", "木村有希", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(170, "survival dAnce ～no no cry more～", "さばいばるだんすのーのーくらいもあ", "小室哲哉", "小室哲哉", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(171, "to you for me", "とぅゆーふぉーみー", "渡部紫緒", "Yoshi", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(172, "ØωØver!!", "おーばー", "前川みく, 多田李衣菜", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(173, "∀nswer", "あんさー", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(174, "あいくるしい", "あいくるしい", "田村歩美", "田村歩美", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(175, "あこがれステッチ", "あこがれすてっち", "磯谷佳江", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(176, "あらかねの器", "あらかねのうつわ", "森由里子", "椎名豪", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(177, "あんきら！？狂騒曲", "あんきらきょうそうきょく", "ヒゲドライバー", "ヒゲドライバー", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(178, "あんずのうた", "あんずのうた", "八城雄太, 佐藤貴文", "佐藤貴文", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(179, "いつかの、いくつかのきみとのせかい", "いつかのいくつかのきみとのせかい", "林英樹", "佐藤純一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(180, "いとしーさー♥", "いとしーさー", "fumi", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(181, "おかしな国のおかし屋さん", "おかしなくにのおかしやさん", "Mitsu, 佐藤貴文", "佐藤貴文", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(182, "おねえちゃんデスコ", "おねえちゃんですこ", "ササキトモコ", "ササキトモコ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(183, "おねだり Shall We～？", "おねだりしゃるうぃー", "佐藤貴文", "佐藤貴文", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(184, "おんなの道は星の道", "おんなのみちはほしのみち", "田村武也", "弦哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(185, "お散歩カメラ", "おさんぽかめら", "イズミカワソラ", "イズミカワソラ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(186, "お願い！シンデレラ", "おねがいしんでれら", "marhy", "内田哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(187, "かぼちゃ姫", "かぼちゃひめ", "ササキトモコ", "ササキトモコ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(188, "きみにいっぱい☆", "きみにいっぱい", "Apis", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(189, "きみにとどけ", "きみにとどけ", "タニザワトモフミ", "タニザワトモフミ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(190, "きゅん・きゅん・まっくす", "きゅんきゅんまっくす", "坂井竜二", "kyo", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(191, "きらりんロボのテーマ", "きらりんろぼのてーま", "YOFFY", "YOFFY", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(192, "き・ま・ぐ・れ☆Café au lait!", "きまぐれかふぇおれ", "Mitsu", "Yoshi", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(193, "こいかぜ", "こいかぜ", "貝田由里子", "椎名豪", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(194, "ここにしか咲かない花", "ここにしかさかないはな", "小渕健太郎", "小渕健太郎", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(195, "この空の下", "このそらのした", "Funta3", "Funta7", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(196, "さよならアロハ", "さよならあろは", "宮崎誠", "宮崎誠", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(197, "さよならアンドロメダ", "さよならあんどろめだ", "MC TC", "Taku Inoue", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(198, "しっぽのきもち", "しっぽのきもち", "谷山浩子", "谷山浩子", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(199, "しゅがーはぁと☆レボリューション", "しゅがーはぁとれぼりゅーしょん", "八城雄太", "山崎真吾", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(200, "じょいふる", "じょいふる", "水野良樹", "水野良樹", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(201, "ずるじゃん", "ずるじゃん", "八城雄太", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(202, "たくさん！", "たくさん", "佐伯youthK", "佐伯youthK", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(203, "つぼみ", "つぼみ", "桜アス恵", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(204, "できたてEvo! Revo! Generation!", "できたてえぼれぼじぇねれーしょん", "三重野瞳", "kyo", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(205, "でれぱ音頭", "でれぱおんど", "原紗友里, 青木瑠璃子", "三浦誠司", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(206, "とどけ！アイドル", "とどけあいどる", "marhy", "内田哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(207, "とんでいっちゃいたいの", "とんでいっちゃいたいの", "佐伯youthK", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(208, "なつっこ音頭", "なつっこおんど", "三浦誠司", "岡野裕次郎", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(209, "にょわにょわーるど☆", "にょわにょわーるど", "夕野ヨシミ", "ARM", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(210, "にんげんっていいな", "にんげんっていいな", "山口あかり", "小林亜星", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(211, "はじめてのチュウ", "はじめてのちゅう", "実川俊晴", "実川俊晴", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(212, "はにかみdays", "はにかみでいす", "森由里子", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(213, "ひまわりマークをさがせ！", "ひまわりまーくをさがせ", "高瀬愛虹", "渡部チェル", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(214, "ぴにゃこら太絵かき歌", "ぴしゃこらたえかきうた", "Cygames", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(215, "ほほえみDiary", "ほほえみだいありー", "Mitsu", "大岩航", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(216, "ましゅまろ☆キッス", "ましゅまろきっす", "トリ音", "トリ音", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(217, "また君に恋してる", "またきみにあいしてる", "松井五郎", "森正明", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(218, "みなぎれ！ボボボンバー", "みなぎれぼぼぼんばー", "狐夢想", "ARM", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(219, "みんなのきもち", "みんなのきもち", "佐藤貴文", "佐藤貴文", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(220, "もりのくにから", "もりのくにから", "fumi", "帆足圭吾", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(221, "わたぐも", "わたぐも", "Manami", "Asu", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(222, "アタシポンコツアンドロイド", "あたしぽんこつあんどろいど", "ササキトモコ", "ササキトモコ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(223, "アップルパイ・プリンセス", "あっぷるぱいぷりんせす", "MC TC, おおくぼひろし", "おおくぼひろし", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(224, "アツアツ♪マカロニグラタン", "あつあつまかろにぐらたん", "ヒゲドライバー", "ヒゲドライバー", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(225, "アルカテイル", "あるかている", "魁", "折戸伸治", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(226, "アンデッド・ダンスロック", "あんでっどだんすろっく", "広川恵一", "広川恵一", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(227, "イケナイGO AHEAD", "いけないごーあへっど", "只野菜摘", "やいり", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(228, "イリュージョニスタ！", "いりゅーじょにすた", "八城雄太", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(229, "ウルトラリラックス", "うるとらりらっくす", "石野卓球", "石野卓球", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(230, "エキストラレボリューション", "えきすとられぼりゅーしょｎ", "ZAQ", "ZAQ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(231, "エチュードは1曲だけ", "えちゅ－どはいっかいだけ", "俊龍", "Sizuk", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(232, "エンジェル ドリーム", "えんじょるどりーむ", "たかみつようこ", "岡部啓一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(233, "エヴリデイドリーム", "えぶりでいどりーむ", "八城雄太", "田草川亮太", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(234, "オウムアムアに幸運を", "おうむあむあにこうふくを", "広川恵一", "広川恵一", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(235, "オタク is LOVE!", "おたくいずらぶ", "ヒゲドライバー", "ヒゲドライバー", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(236, "オヤマトペ♪", "おやまとぺ", "fumi", "大岩航", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(237, "オルゴールの小箱", "おるごーるのこばこ", "森由里子", "高橋浩平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(238, "オレンジタイム", "おれんじたいむ", "広川恵一", "広川恵一", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(239, "ガッツだぜ！！", "がっつだぜ", "トータス松本", "トータス松本", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(240, "ガールズ・イン・ザ・フロンティア", "がーるずいんざふろんてぃあ", "八城雄太", "設楽哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(241, "キセキの証", "きせきのあかし", "渡部紫緒", "坂部剛", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(242, "キミとボクのミライ", "きみとぼくとみらい", "Cygames, maimie", "UEMATSU NOBUO, NARITA TSUTOMU", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(243, "キミのそばでずっと", "きみのそばでずっと", "荘野ジュリ", "坪田修平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(244, "キラッ！満開スマイル", "きらっまんかいすまいる", "ササキトモコ", "ササキトモコ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(245, "ギュっとMilky Way", "ぎゅっとみるきーうぇい", "高瀬愛虹", "渡部チェル", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(246, "クレイジークレイジー", "くれいじーくれいじー", "MC TC", "Taku Inoue", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(247, "ココカラミライヘ！", "ここからみらいへ", "遠藤フビト", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(248, "ゴキゲンParty Night", "ごきげんぱーてぃーないと", "森由里子", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(249, "サイキック！ぱーりーないと☆", "さいきっくばーりーないと", "坂井竜二", "山崎真吾", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(250, "サニードロップ", "さにーどろっぷ", "磯谷佳江", "seibin", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(251, "サマカニ！！", "さまかに", "宮崎誠", "宮崎誠", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(252, "サヨナラバス", "さよならばす", "北川悠仁", "北川悠仁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(253, "サラバ、愛しき悲しみたちよ", "さらばいとしきかなしみたちよ", "岩里祐穂", "布袋寅泰", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(254, "ショコラ・ティアラ", "しょこらてぃあら", "古屋真", "kyo", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(255, "スカイクラッドの観測者", "すかいくらっどのかんそくしゃ", "志倉千代丸", "志倉千代丸", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(256, "ススメ☆オトメ ～jewel parade～", "すすめおとめじゅえりーぱれーど", "森由里子", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(257, "スターラブレイション", "すたーらぶれいしょん", "ふるっぺ, 森さん, Litz", "ふるっぺ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(258, "ステップ！", "すてっぷ", "Manami", "no_my", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(259, "ステップ＆スキップ", "すてっぷすきっぷ", "朝倉路", "石濱翔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(260, "ストリート・ランウェイ", "すとりーとらんうぇい", "烏屋茶房", "石濱翔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(261, "スパイスパラダイス", "すぱいすぱらだいす", "宮崎誠", "宮崎誠", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(262, "スローライフ・ファンタジー", "すろーらいふふぁんたじー", "八城雄太", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(263, "ソウソウ", "そうそう", "MC TC", "Taku Inoue", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(264, "タッタ", "たった", "北川悠仁", "北川悠仁, JIN", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(265, "タッチ", "たっち", "康珍化", "芹澤廣明", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(266, "ダイアモンド・アテンション", "だいあもんどあてんしょん", "eNu", "設楽哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(267, "ツインテールの風", "ついんてーるのかぜ", "森由里子", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(268, "ツバサ", "すばさ", "真戸原直人", "真戸原直人", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(269, "デレぱにぱにック", "でれぱにぱにっく", "原紗友里, 青木瑠璃子", "長谷川智樹", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(270, "デレパノココロ", "でれぱのこころ", "原紗友里, 青木瑠璃子", "AJURIKA", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(271, "トキメキは赤くて甘い", "ときめきはあかくてあまい", "烏屋茶房", "烏屋茶房", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(272, "トロピカルガール", "とろぴかるがーる", "磯谷佳江", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(273, "ドレミファクトリー！", "どれみふぁくとりー", "俊龍", "Sizuk", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(274, "ナンダカンダ", "なんだかんだ", "GAKU-MC", "浅倉大介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(275, "ニャンと☆スペクタクル", "にゃんとすぺくたる", "ミト", "ミト", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(276, "ハイファイ☆デイズ", "はいふぁいでいず", "宮崎誠", "宮崎誠", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(277, "ハピガ！", "はぴが", "ミト", "ミト", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(278, "ハミングがきこえる", "はみんぐがきこえる", "さくらももこ", "小山田圭吾", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(279, "ハレ晴レユカイ", "はれはれゆかい", "畑亜貴", "田代智一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(280, "ハーモニクス", "はーもにくす", "坂井季乃", "高橋諒", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(281, "バベル", "ばべる", "ミフメイ", "ミフメイ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(282, "パステルピンクな恋", "ぱすてるぴんくなこい", "marhy", "内田哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(283, "パ・リ・ラ", "ぱりら", "俊龍", "Sizuk", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(284, "ヒカリ→シンコキュウ→ミライ", "ひかりしんこきゅうみらい", "やいり", "やいり", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(285, "ヒトトキトキメキ", "ひとときときめき", "山本真央樹", "山本真央樹", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(286, "ヒーローヴァーサスレイナンジョー", "ひーろーばーさすれいなんじょー", "藤林聖子", "渡辺宙明", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(287, "ピンキージョーンズ", "ぴんきーじょーんず", "村野直球", "NARASAKI", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(288, "フレデリカ、猫やめるよ", "ふれでりかねこやめるよ", "ササキトモコ", "ササキトモコ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(289, "プライスレス ドーナッCyu♡", "ぷらいすれすどーなっちゅ", "山崎真吾", "山崎真吾", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(290, "ペッパー警部", "ぺっぱーけいぶ", "阿久悠", "都倉俊一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(291, "マイ・スイート・ハネムーン", "まいすいーとはねむーん", "滝澤俊輔", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(292, "ミツボシ☆☆★", "みつぼし", "八城雄太", "kyo", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(293, "ミラクルテレパシー", "みらくるてれぱしー", "日暮裕紀", "日暮裕紀", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(294, "ミラーボール・ラブ", "みらーぼーるらぶ", "MC TC", "Taku Inoue", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(295, "メッセージ", "めっせーじ", "遠藤フビト", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(296, "メトロポリタン美術館", "めとろぽりたんびじゅつかん", "大貫妙子", "大貫妙子", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(297, "メルヘン∞メタモルフォーゼ！", "めるへんめたもるふぉーぜ", "八城雄太", "佐藤貴文", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(298, "メルヘンデビュー", "めるへんでびゅー", "夕野ヨシミ", "ARM", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(299, "モザイクカケラ", "もざいくかけら", "石田順三", "石田順三", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(300, "モーレツ★世直しギルティ！", "もーれつよなおしぎるてぃ", "fumi", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(301, "ラジオ体操第一", "らじおたいそうだいいち", "－", "服部正", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(302, "ラジオ体操第二", "らじおたいそうだいに", "－", "團伊玖磨", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(303, "ラブリー", "らぶりー", "小沢健二", "小沢健二", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(304, "ラブレター", "らぶれたー", "桜アス恵", "岡野裕次郎", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(305, "ラヴィアンローズ", "らびあんろーず", "小金井つくも", "渡部チェル", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(306, "リトルリドル", "りとるりどる", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(307, "リバイブ", "りばいぶ", "Kanata Okajima, Daisuke Nakamura, YUTA", "Daisuke Nakamura", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(308, "ルル", "るる", "ティカ・α", "ティカ・α", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(309, "レッド・ソール", "れっどそーる", "月丘りあ子", "塩原大貴", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(310, "ロックン・オムレツ", "ろっくんおむれつ", "森高千里", "伊秩弘将", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(311, "ヴィーナスシンドローム", "びーなすしんどろーむ", "古屋真", "kyo", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(312, "不埒なCANVAS", "ふらちなきゃんばす", "只野菜摘", "烏屋茶房", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(313, "不思議なピーチパイ", "ふしぎなぴーちぱい", "安井かずみ", "加藤和彦", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(314, "世界滅亡 or KISS", "せかいめつぼうおあきす", "八城雄太", "坪田修平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(315, "亜麻色の髪の乙女", "あまいろのかみのおとめ", "橋本淳", "すぎやまこういち", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(316, "全力☆Summer!", "ぜんりょくさまー", "atsuko", "atsuko, KATSU", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(317, "共鳴世界の存在論", "きょうめいせかいのおんとろじー", "烏屋茶房", "烏屋茶房", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(318, "冒険でしょでしょ？", "ぼうけんでしょでしょ", "畑亜貴", "冨田暁子", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(319, "冬空プレシャス", "ふゆぞらぷれしゃす", "朝倉路", "石濱翔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(320, "凸凹スピードスター", "でこぼですぴーどすたー", "ゆよゆっぺ", "ゆよゆっぺ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(321, "初夢をあなたと", "はつゆめをあなたに", "出口遼", "出口遼", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(322, "印象", "いんしょう", "烏屋茶房", "篠崎あやと", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(323, "友達の唄", "ともだちのうた", "北川悠仁", "北川悠仁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(324, "双翼の独奏歌", "そうよくのありあ", "マチゲリータ, 烏屋茶房", "Powerless", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(325, "反逆的同一性 -Rebellion Identity-", "りべりおんあいでんてぃてぃ", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(326, "君のステージ衣装、本当は…", "きみのすてーじいしょうほんとうは", "俊龍", "Sizuk", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(327, "君の知らない物語", "きみのしらないものがたり", "ryo", "ryo", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(328, "君の青春は輝いているか", "きみのせいしゅんはかがやいているか", "ジェームス三木", "三木たかし", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(329, "君への詩", "きみへのうた", "三浦誠司", "三浦誠司", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(330, "命燃やして恋せよ乙女", "いのちもやしてこいせよおとめ", "森由里子", "TAKT", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(331, "咲いてJewel", "さいてじゅえる", "俊龍", "俊龍", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(332, "堕ちる果実", "おちるかじつ", "只野菜摘", "広川恵一", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(333, "夏恋 -NATSU KOI-", "なつこい", "AJURIKA", "AJURIKA", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(334, "夏色", "なついろ", "北川悠仁", "北川悠仁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(335, "夕映えプレゼント", "ゆうばえぷれぜんと", "遠藤フビト", "Yoshi", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(336, "夢をのぞいたら", "ゆめをのぞいたら", "佐伯youthK", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(337, "夢幻ノ救憐唱 ～堕チル星ノ調ベ～", "ゆめのきりえおちるほしのしらべ", "やいり, 烏屋茶房", "Powerless", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(338, "夢色ハーモニー", "ゆめいろはーもにー", "遠藤フビト", "内田哲也", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(339, "大きな古時計", "おおきなふるどけい", "Henry Clay Work", "Henry Clay Work", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(340, "大河よ共に泣いてくれ", "たいがよともにないてくれ", "古屋真", "加藤裕介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(341, "大都会交響楽", "だいとかいこうきょうきょく", "小西康陽", "小西康陽", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(342, "天城越え", "あまぎごえ", "吉岡治", "弦哲也", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(343, "太陽の絵の具箱", "たいようのえのぐばこ", "トリ音", "トリ音", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(344, "奏 (かなで)", "かなで", "スキマスイッチ", "スキマスイッチ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(345, "女の子は誰でも", "おんなのこはだれでも", "椎名林檎", "椎名林檎", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(346, "学園天国", "がくえんてんごく", "阿久悠", "井上忠夫", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(347, "守ってあげたい", "まもってあげたい", "松任谷由実", "松任谷由実", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(348, "実用音楽その1 閉店の音楽 別れのワルツ(蛍の光)", "じつようおんがくそのいちへいてんのおんがくわかれのわるつほたるのひかり", "スコットランド民謡 ", "スコットランド民謡 ", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(349, "実用音楽その2 安眠とやすらぎの音楽　シューベルトの子守歌", "じつようおんがくそのにあんみんとやすらぎのおんがくしゅーべるとのこもりうた", "Matthias Claudius", "Franz Peter Schubert", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(350, "実用音楽その3 祝賀の日本伝統音楽 高砂", "じつようおんがくそのさんしゅくがのにほんでんとうおんがくたかさご", "日本民謡", "日本民謡", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(351, "小さな恋の密室事件", "ちいさなこいのみっしつじけん", "八城雄太, 佐藤貴文", "佐藤貴文", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(352, "幸せの法則～ルール～", "しあわせのるーる", "内海孝彰", "内海孝彰", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(353, "弾丸サバイバー", "だんがんさばいばー", "宮崎誠", "宮崎誠", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(354, "徒花ネクロマンシー", "あだばなねくろまんしー", "古屋真", "加藤裕介", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(355, "心もよう", "こころもよう", "遠藤フビト", "滝澤俊輔", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(356, "思い出じゃない今日を", "おもいでじゃないいまを", "steμ", "steμ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(357, "恋が咲く季節", "はながさくきせつ", "ESTi", "ESTi", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(358, "恋のHamburg♪", "こいのはんばーぐ", "柿埜嘉奈子", "kyo", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(359, "恋色エナジー", "こいいろえなじー", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(360, "悲しみをやさしさに", "かなしみをやさしさに", "tetsuhiko", "tetsuhiko, Tomoji Sogawa", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(361, "情熱ファンファンファーレ", "じょうねつふぁんふぁーれ", "no_my", "no_my", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(362, "愛の讃歌", "あいのさんか", "小金井つくも", "坪田修平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(363, "愛は元気です。", "あいはげんきです", "戸沢暢美", "谷村有美", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(364, "日々あどべんちゃーなのでしてー", "ひびあどべんちゃーなのでしてー", "山本真央樹", "山本真央樹", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(365, "日曜日はダメダメよ", "にちようびはだめだめよ", "小西康陽", "小西康陽", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(366, "明日また会えるよね", "あしたまたあえるね", "Funta3", "Funta7", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(367, "星環世界", "せいかんせかい", "八城雄太", "ミフメイ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(368, "春恋フレーム", "はるこいふれーむ", "磯谷佳江", "藤長陽太", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(369, "時を刻む唄", "ときをきざむうた", "麻枝准", "麻枝准", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(370, "月のしずく", "つきのしずく", "Satomi", "松本良喜", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(371, "未完成の歴史", "みかんせいのれきし", "及川眠子", "椎名豪", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(372, "♡桃色片想い♡", "ももいろかたおもい", "つんく", "つんく", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(373, "桜の頃", "さくらのころ", "桜アス恵", "隠田遼平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(374, "桜の風", "さくらのかぜ", "森由里子", "田中秀和", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(375, "楽園", "らくえん", "渡部量", "渡部量", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(376, "毒茸伝説", "どくきのこでんせつ", "LindaAI-CUE, 桜アス恵", "LindaAI-CUE", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(377, "気まぐれロマンティック", "きまぐれろまんてぃっく", "水野良樹", "水野良樹", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(378, "気分爽快", "きぶんそうかい", "森高千里", "黒沢健一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(379, "気持ちいいよね 一等賞！", "きもちいいよねいっとうしょう", "Funta3", "Funta7", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(380, "泡沫のアイオーン", "うたかたのあいおーん", "kyo", "山本真央樹", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(381, "流れ星キセキ", "ながれぼしきせき", "小金井つくも", "渡部チェル", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(382, "満願成就♪巫女の神頼み！", "まんがんじょうじゅみこのかみだのみ", "夕野ヨシミ", "ARM", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(383, "炎の華", "ほのおのはな", "磯谷佳江", "高取ヒデアキ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(384, "無重力シャトル", "むじょうりょくしゃとる", "北川悠仁", "北川悠仁", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(385, "熱血乙女A", "ねっけつしょうじょえー", "mft", "Jesahm", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(386, "狙いうち", "ねらいうち", "阿久悠", "都倉俊一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(387, "生存本能ヴァルキュリア", "せいぞんほんのうばるきゅりあ", "朝倉路", "渡部チェル", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(388, "碧いうさぎ", "あおいうさぎ", "牧穂エミ", "織田哲郎", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(389, "祈りの花", "いのりのはな", "トリ音", "トリ音", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(390, "私色のプレリュード", "わたしいろのぷれりゅーど", "烏屋茶房", "篠崎あやと, 橘亮祐", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(391, "私色ギフト", "わたしいろぎふと", "朝倉路", "渡部チェル", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(392, "秋めいて Ding Dong Dang!", "あきめいてでぃんどんだん", "夕野ヨシミ, 弧夢想", "ARM", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(393, "秋風に手を振って", "あきいろにてをふって", "森由里子", "Yoshi", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(394, "秘密のトワレ", "ひみつのとわれ", "ササキトモコ", "ササキトモコ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(395, "空と風と恋のワルツ", "そらとかぜとこいのわるつ", "トリ音", "トリ音", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(396, "空想探査計画", "くうそうたんさけいかく", "重田祐介", "佐藤貴文", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(397, "紅", "くれない", "YOSHIKI", "YOSHIKI", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(398, "純情Midnight伝説", "じゅんじょうみっどないとでんせつ", "磯谷佳江", "小野貴光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(399, "純情接近STORY", "じゅんじょうせっきんすとーりー", "森由里子", "神前暁", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(400, "絶対特権主張しますっ！", "ぜったいとっけんしゅちょうします", "坂井竜二", "山崎真吾", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(401, "美に入り彩を穿つ", "びにいりてさいをうがつ", "野口圭", "渡部チェル", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(402, "義勇忍侠花吹雪", "ぎゆうにんきょうはなふぶき", "ミズノゲンキ", "睦月周平", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(403, "花のことば", "はなのことば", "mft", "高田龍一", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(404, "花簪 HANAKANZASHI", "はなかんざし", "夕野ヨシミ", "ARM", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(405, "華蕾夢ミル狂詩曲〜魂ノ導〜", "つぼみゆめみるらぶそでぃーああるまのみちびき", "東ノ獄彩", "浩川卿中二", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(406, "蒼穹", "そうきゅう", "atsuko", "atsuko, KATSU", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(407, "薄紅", "うすべに", "内海孝彰", "内海孝彰", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(408, "薄荷 -ハッカ-", "はっか", "いつきおと", "泉典孝", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(409, "虹", "にじ", "北川悠仁", "北川悠仁", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(410, "蛍火", "ほたるび", "須藤まゆみ", "椎名豪", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(411, "行くぜっ！怪盗少女", "いくぜっかいとうしょうじょ", "前山田健一", "前山田健一", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(412, "見上げてごらん夜の星を", "みあげてごらんよるのほしを", "永六輔", "いずみたく", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(413, "誰より好きなのに", "だれよりもすきなのに", "古内東子", "古内東子", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(414, "谷の底で咲く花は", "たにのそこでさくはなは", "八城雄太", "岡部啓一", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(415, "踊りまくろ☆ダンシング・ナイト", "おどりまくろだんしんぐないと", "YOFFY", "YOFFY", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(416, "躍るFLAGSHIP", "おどるふらっぐしっぷ", "只野菜摘", "ミフメイ", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(417, "輝く世界の魔法", "かがやくせかいのまほう", "yura", "小西裕子", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(418, "輝け！ビートシューター", "かがやけびーとしゅーたー", "YOFFY", "YOFFY", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(419, "追い風Running", "おいかぜらんにんぐ", "ミズノゲンキ", "HONY, Shouya Nmai", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(420, "遠く遠く", "とおくとおく", "槇原敬之", "槇原敬之", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(421, "銀のイルカと熱い風", "ぎんのいるかとあついかぜ", "森由里子", "俊龍", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(422, "銀河図書館", "ぎんがとしょかん", "烏屋茶房", "烏屋茶房", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(423, "離れていても", "はなれていても", "岡本真夜", "岡本真夜", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(424, "雪の華", "ゆきのはな", "Satomi", "松本良喜", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(425, "青の一番星", "あおのいちばんぼし", "夕野ヨシミ", "ARM", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(426, "青空エール", "あおぞらえーる", "eNu", "川島弘光", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(427, "青空リレーション", "あおぞらりれーしょん", "Apis", "岡野裕次郎", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(428, "風になりたい", "かぜになりたい", "宮沢和史", "宮沢和史", 1, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(429, "風色メロディ", "かぜいろめろでぃ", "トリ音", "トリ音", 0, 0);
insert into cinderella.musics(`id`, `name`, `kana`, `lyrics`, `compose`, `cover`, `inst`) values(430, "鳥の詩", "とりのうた", "麻枝准", "折戸伸治", 1, 0);
