INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (1, "Never say never", 1, 1, 90);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (2, "ドラマ「目指せ!シンデレラNO.1! -渋谷凛編-」", 1, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (3, "Never say never(オリジナル・カラオケ)", 1, 3, 90);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (4, "ボーナス・トラック", 1, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (5, "あんずのうた", 2, 1, 178);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (6, "ドラマ「目指せ!シンデレラNO.1! -双葉杏編-」", 2, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (7, "あんずのうた(オリジナル・カラオケ)", 2, 3, 178);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (8, "ボーナス・トラック", 2, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (9, "ショコラ・ティアラ", 3, 1, 254);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (10, "ドラマ「目指せ!シンデレラNO.1! -三村かな子編-」", 3, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (11, "ショコラ・ティアラ(オリジナル・カラオケ)", 3, 3, 254);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (12, "ボーナス・トラック", 3, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (13, "こいかぜ", 4, 1, 193);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (14, "ドラマ「目指せ!シンデレラNO.1! -高垣楓編-」", 4, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (15, "こいかぜ(オリジナル・カラオケ)", 4, 3, 193);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (16, "ボーナス・トラック", 4, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (17, "DOKIDOKIリズム", 5, 1, 23);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (18, "ドラマ「目指せ!シンデレラNO.1! -城ヶ崎莉嘉編-」", 5, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (19, "DOKIDOKIリズム(オリジナル・カラオケ)", 5, 3, 23);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (20, "ボーナス・トラック", 5, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (21, "華蕾夢ミル狂詩曲〜魂ノ導〜", 6, 1, 405);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (22, "ドラマ「目指せ!シンデレラNO.1! -神崎蘭子編-」", 6, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (23, "ドラマ「目指せ!シンデレラNO.1! -神崎蘭子編-」(副音声付きver.)", 6, 3, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (24, "華蕾夢ミル狂詩曲〜魂ノ導〜(オリジナル・カラオケ)", 6, 4, 405);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (25, "ボーナス・トラック", 6, 5, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (26, "おねだり Shall We 〜?", 7, 1, 183);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (27, "ドラマ「目指せ!シンデレラNO.1! -前川みく編-」", 7, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (28, "おねだり Shall We 〜?(オリジナル・カラオケ)", 7, 3, 183);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (29, "ボーナス・トラック", 7, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (30, "ましゅまろ☆キッス", 8, 1, 216);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (31, "ドラマ「目指せ!シンデレラNO.1! -諸星きらり編-」", 8, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (32, "ましゅまろ☆キッス(オリジナル・カラオケ)", 8, 3, 216);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (33, "ボーナス・トラック", 8, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (34, "TOKIMEKIエスカレート", 9, 1, 139);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (35, "ドラマ「目指せ!シンデレラNO.1! -城ヶ崎美嘉-」", 9, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (36, "TOKIMEKIエスカレート(オリジナル・カラオケ)", 9, 3, 139);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (37, "ボーナス・トラック", 9, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (38, "S(mile)ING!", 10, 1, 117);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (39, "ドラマ「目指せ!シンデレラNO.1! -島村卯月-」", 10, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (40, "S(mile)ING!(オリジナル・カラオケ)", 10, 3, 117);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (41, "ボーナス・トラック", 10, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (42, "Naked Romance", 11, 1, 84);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (43, "ドラマ「目指せ!シンデレラNO.1! -小日向美穂編-」", 11, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (44, "Naked Romance(オリジナル・カラオケ)", 11, 3, 84);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (45, "ボーナス・トラック", 11, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (46, "Twilight Sky", 12, 1, 148);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (47, "ドラマ「目指せ!シンデレラNO.1! -多田李衣菜編-」", 12, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (48, "Twilight Sky(オリジナル・カラオケ)", 12, 3, 148);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (49, "ボーナス・トラック", 12, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (50, "アップルパイ・プリンセス", 13, 1, 223);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (51, "ドラマ「目指せ!シンデレラNO.1! -十時愛梨編-」", 13, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (52, "アップルパイ・プリンセス(オリジナル・カラオケ)", 13, 3, 223);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (53, "ボーナス・トラック", 13, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (54, "Angel Breeze", 14, 1, 8);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (55, "ドラマ「目指せ!シンデレラNO.1! -川島瑞樹編-」", 14, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (56, "Angel Breeze(オリジナル・カラオケ)", 14, 3, 8);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (57, "ボーナス・トラック", 14, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (58, "ミツボシ☆☆★", 15, 1, 292);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (59, "ドラマ「目指せ!シンデレラNO.1! -本田未央編-」", 15, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (60, "ミツボシ☆☆★(オリジナル・カラオケ)", 15, 3, 292);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (61, "ボーナス・トラック", 15, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (62, "お願い!シンデレラ(M@STER VERSION)", 16, 1, 186);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (63, "お願い!シンデレラ(Cute VERSION)", 16, 2, 186);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (64, "お願い!シンデレラ(Cool VERSION)", 16, 3, 186);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (65, "お願い!シンデレラ(Passion VERSION)", 16, 4, 186);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (66, "あんきら劇場", 16, 5, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (67, "お願い!シンデレラ(省エネver)", 16, 6, 186);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (68, "お願い!シンデレラ(オリジナルカラオケ)", 16, 7, 186);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (69, "熱血乙女A", 17, 1, 385);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (70, "ドラマ「目指せ!シンデレラNO.1! -日野茜編-」", 17, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (71, "熱血乙女A(オリジナル・カラオケ)", 17, 3, 385);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (72, "ボーナス・トラック", 17, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (73, "Romantic Now", 18, 1, 116);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (74, "ドラマ「目指せ!シンデレラNO.1! -赤城みりあ編-」", 18, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (75, "Romantic Now(オリジナル・カラオケ)", 18, 3, 116);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (76, "ボーナス・トラック", 18, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (77, "メルヘンデビュー", 19, 1, 298);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (78, "ドラマ「目指せ!シンデレラNO.1! -安部菜々編-」", 19, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (79, "メルヘンデビュー(オリジナル・カラオケ)", 19, 3, 298);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (80, "ボーナス・トラック", 19, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (81, "ヴィーナスシンドローム", 20, 1, 311);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (82, "ドラマ「目指せ!シンデレラNO.1! -新田美波編-」", 20, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (83, "ヴィーナスシンドローム(オリジナル・カラオケ)", 20, 3, 311);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (84, "ボーナス・トラック", 20, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (85, "To my darling…", 21, 1, 142);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (86, "ドラマ「目指せ!シンデレラNO.1! -輿水幸子編-」", 21, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (87, "To my darling…(オリジナル・カラオケ)", 21, 3, 142);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (88, "ボーナス・トラック", 21, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (89, "輝く世界の魔法(M@STER VERSION)", 22, 1, 417);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (90, "ドラマパート", 22, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (91, "輝く世界の魔法(NEW GENERATIONS VERSION)", 22, 3, 417);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (92, "輝く世界の魔法(オリジナル・カラオケ)", 22, 4, 417);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (93, "エヴリデイドリーム", 23, 1, 233);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (94, "ドラマ「目指せ!シンデレラNO.1! -佐久間まゆ編-」", 23, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (95, "エヴリデイドリーム(オリジナル・カラオケ)", 23, 3, 233);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (96, "ボーナス・トラック", 23, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (97, "小さな恋の密室事件", 24, 1, 351);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (98, "ドラマ「目指せ!シンデレラNO.1! -白坂小梅編-」", 24, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (99, "小さな恋の密室事件(オリジナル・カラオケ)", 24, 3, 351);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (100, "ボーナス・トラック", 24, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (101, "風色メロディ", 25, 1, 429);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (102, "ドラマ「目指せ!シンデレラNO.1! -緒方智絵里編-」", 25, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (103, "風色メロディ(オリジナル・カラオケ)", 25, 3, 429);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (104, "ボーナス・トラック", 25, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (105, "You're stars shine on me", 26, 1, 161);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (106, "ドラマ「目指せ!シンデレラNO.1! -アナスタシア編-」	", 26, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (107, "You're stars shine on me(オリジナル・カラオケ)", 26, 3, 161);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (108, "ボーナス・トラック", 26, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (109, "お散歩カメラ", 27, 1, 185);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (110, "ドラマ「目指せ!シンデレラNO.1! -高森藍子編-」", 27, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (111, "お散歩カメラ(オリジナル・カラオケ)", 27, 3, 185);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (112, "ボーナス・トラック", 27, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (113, "毒茸伝説", 28, 1, 376);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (114, "ドラマ「目指せ!シンデレラNO.1! -星輝子編-」", 28, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (115, "毒茸伝説(オリジナル・カラオケ)", 28, 3, 376);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (116, "ボーナス・トラック", 28, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (117, "2nd SIDE", 29, 1, 5);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (118, "ドラマ「目指せ!シンデレラNO.1! -神谷奈緒編-」", 29, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (119, "2nd SIDE(オリジナル・カラオケ)", 29, 3, 5);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (120, "ボーナス・トラック", 29, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (121, "薄荷 -ハッカ-", 30, 1, 408);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (122, "ドラマ「目指せ!シンデレラNO.1! -北条加蓮編-」", 30, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (123, "薄荷 -ハッカ-(オリジナル・カラオケ)", 30, 3, 408);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (124, "ボーナス・トラック", 30, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (125, "花簪 HANAKANZASHI", 31, 1, 404);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (126, "ドラマ「目指せ!シンデレラNO.1! -小早川紗枝編-」", 31, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (127, "花簪 HANAKANZASHI(オリジナル・カラオケ)", 31, 3, 404);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (128, "ボーナス・トラック", 31, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (129, "ミラクルテレパシー", 32, 1, 293);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (130, "ドラマ「目指せ!シンデレラNO.1! -堀裕子編-」", 32, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (131, "ミラクルテレパシー(オリジナル・カラオケ)", 32, 3, 293);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (132, "ボーナス・トラック", 32, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (133, "We're the friends!", 33, 1, 154);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (134, "メッセージ", 33, 2, 295);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (135, "ドラマパート", 33, 3, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (136, "We're the friends!(オリジナル・カラオケ)", 33, 4, 154);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (137, "メッセージ(オリジナル・カラオケ)", 33, 5, 295);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (138, "Star!!", 34, 1, 132);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (139, "お願い!シンデレラ", 34, 2, 186);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (140, "メッセージ", 34, 3, 295);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (141, "Star!!(オリジナル・カラオケ)", 34, 4, 132);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (142, "Bright Blue", 35, 1, 15);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (143, "ドラマ「目指せ!シンデレラNO.1! -鷺沢文香編-」", 35, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (144, "Bright Blue(オリジナル・カラオケ)", 35, 3, 15);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (145, "ボーナス・トラック", 35, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (146, "気持ちいいよね 一等賞!", 36, 1, 379);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (147, "ドラマ「目指せ!シンデレラNO.1! -姫川友紀編-」", 36, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (148, "気持ちいいよね 一等賞!(オリジナル・カラオケ)", 36, 3, 379);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (149, "ボーナス・トラック", 36, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (150, "き・ま・ぐ・れ☆Cafe au lait!", 37, 1, 192);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (151, "ドラマ「目指せ!シンデレラNO.1! -宮本フレデリカ編-」", 37, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (152, "き・ま・ぐ・れ☆Cafe au lait!(オリジナル・カラオケ)", 37, 3, 192);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (153, "ボーナス・トラック", 37, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (154, "Hotel Moonside", 38, 1, 56);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (155, "ドラマ「目指せ!シンデレラNO.1! -速水奏編-」", 38, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (156, "Hotel Moonside(オリジナル・カラオケ)", 38, 3, 56);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (157, "ボーナス・トラック", 38, 4, 65535);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (158, "みんなのきもち", 39, 1, 219);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (159, "ドラマ「目指せ!シンデレラNO.1! -市原仁奈編-」", 39, 2, 65534);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (160, "みんなのきもち(オリジナル・カラオケ)", 39, 3, 219);
INSERT INTO `cinderella`.`tracks` (`id`, `name`, `disc_id`, `track`, `music_id`) VALUES (161, "ボーナス・トラック", 39, 4, 65535);
