insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(  1,	"相原雪乃",				"あいはらゆきの",		"Cu",	"0214", null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(  2,	"赤西瑛梨華",			"あかにしえりか",		"Cu",	"0707",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(  3,	"浅野風香",				"あさのふゆか",			"Cu",	"0211",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(  4,	"安部菜々",				"あべなな",				"Cu",	"0515",	"三宅麻理恵");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(  5,	"有浦柑奈",				"ありうらかんな",		"Cu",	"0306",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(  6,	"安斎都",				"あんざいみやこ",		"Cu",	"0106",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(  7,	"五十嵐響子",			"いがらしきょうこ",		"Cu",	"0810",	"種﨑敦美");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(  8,	"池袋晶葉",				"いけぶくろあきは",		"Cu",	"0610",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(  9,	"一ノ瀬志希",			"いちのせしき",			"Cu",	"0530",	"藍原ことみ");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 10,	"今井加奈",				"いまいかな",			"Cu",	"0303",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 11,	"井村雪菜",				"いむらせつな",			"Cu",	"0827",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 12,	"江上椿",				"えがみつばき",			"Cu",	"0206",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 13,	"太田優",				"おおたゆう",			"Cu",	"0128",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 14,	"大西由里子",			"おおにしゆりこ",		"Cu",	"0320",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 15,	"大沼くるみ",			"おおぬまくるみ",		"Cu",	"0330",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 16,	"大原みちる",			"おおはらみちる",		"Cu",	"0412",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 17,	"緒方智絵里",			"おがたちえり",			"Cu",	"0611",	"大空直美");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 18,	"奥山沙織",				"おくやまさおり",		"Cu",	"0612",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 19,	"乙倉悠貴",				"おとくらゆうき",		"Cu",	"1006",	"中島由貴");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 20,	"日下部若葉",			"くさかべわかば",		"Cu",	"0504",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 21,	"工藤忍",				"くどうしのぶ",			"Cu",	"0309",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 22,	"クラリス",				"くらりす",				"Cu",	"0826",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 23,	"栗原ネネ",				"くりはらねね",			"Cu",	"0909",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 24,	"黒埼ちとせ",			"くろさきちとせ",		"Cu",	"1110",	"佐倉薫");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 25,	"古賀小春",				"こがこはる",			"Cu",	"0401",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 26,	"輿水幸子",				"こしみずさちこ",		"Cu",	"1125",	"竹達彩奈");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 27,	"小早川紗枝",			"こばやかわさえ",		"Cu",	"1018",	"立花理香");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 28,	"小日向美穂",			"こひなたみほ",			"Cu",	"1216",	"津田美波");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 29,	"西園寺琴歌",			"さいおんじことか",		"Cu",	"0123",	"安齋由香里");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 30,	"榊原里美",				"さかきばらさとみ",		"Cu",	"0827",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 31,	"佐久間まゆ",			"さくままゆ",			"Cu",	"0907",	"牧野由依");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 32,	"櫻井桃華",				"さくらいももか",		"Cu",	"0408",	"照井春佳");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 33,	"椎名法子",				"しいなのりこ",			"Cu",	"1010",	"都丸ちよ");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 34,	"島村卯月",				"しまむらうづき",		"Cu",	"0424",	"大橋彩香");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 35,	"白菊ほたる",			"しらぎくほたる",		"Cu",	"0419",	"天野聡美");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 36,	"白雪千夜",				"しらゆきちよ",			"Cu",	"0204",	"関口理咲");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 37,	"涼宮星花",				"すずみやせいか",		"Cu",	"0828",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 38,	"関裕美",				"せきひろみ",			"Cu",	"0817",	"会沢紗弥");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 39,	"月宮雅",				"つきみやみやび",		"Cu",	"1030",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 40,	"辻野あかり",			"つじのあかり",			"Cu",	"1105",	"梅澤めぐ");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 41,	"道明寺歌鈴",			"どうみょうじかりん",	"Cu",	"0101",	"新田ひより");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 42,	"長富蓮実",				"ながとみはすみ",		"Cu",	"0319",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 43,	"中野有香",				"なかのゆうか",			"Cu",	"0323",	"下地紫野");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 44,	"丹羽仁美",				"にわひとみ",			"Cu",	"0604",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 45,	"早坂美玲",				"はやさかみれい",		"Cu",	"0509",	"朝井彩加");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 46,	"原田美世",				"はらだみよ",			"Cu",	"1114",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 47,	"兵藤レナ",				"ひょうどうれな",		"Cu",	"1003",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 48,	"福山舞",				"ふくやままい",			"Cu",	"0121",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 49,	"藤本里奈",				"ふじもとりな",			"Cu",	"1014",	"金子真由美");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 50,	"双葉杏",				"ふたばあんず",			"Cu",	"0902",	"五十嵐裕美");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 51,	"前川みく",				"まえかわみく",			"Cu",	"0222",	"高森奈津美");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 52,	"松原早耶",				"まつばらさや",			"Cu",	"1228",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 53,	"間中美里",				"まなかみさと",			"Cu",	"1106",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 54,	"水本ゆかり",			"みずもとゆかり",		"Cu",	"1018",	"藤田茜");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 55,	"三村かな子",			"みむらかなこ",			"Cu",	"0106",	"大坪由佳");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 56,	"宮本フレデリカ",		"みやもとふれでりか",	"Cu",	"0214",	"髙野麻美");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 57,	"棟方愛海",				"むなかたあつみ",		"Cu",	"0801",	"藤本彩花");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 58,	"村松さくら",			"まつむらさくら",		"Cu",	"0327",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 59,	"持田亜里沙",			"もちだありさ",			"Cu",	"0824",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 60,	"桃井あずき",			"ももいあずさ",			"Cu",	"0707",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 61,	"楊菲菲",				"やおふぇいふぇい",		"Cu",	"0929",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 62,	"柳清良",				"やなぎきよら",			"Cu",	"0512",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 63,	"柳瀬美由紀",			"やなせみゆき",			"Cu",	"0316",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 64,	"遊佐こずえ",			"ゆさこずえ",			"Cu",	"0219",	"花谷麻妃");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 65,	"横山千佳",				"よこやまちか",			"Cu",	"1218",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 66,	"相川千夏",				"あいかわちなつ",		"Co",	"1111",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 67,	"浅利七海",				"あさりななみ",			"Co",	"1009",	"井上ほの花");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 68,	"アナスタシア",			"あなすたしあ",			"Co",	"0919",	"上坂すみれ");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 69,	"綾瀬穂乃香",			"あやせほのか",			"Co",	"0529",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 70,	"荒木比奈",				"あらきひな",			"Co",	"0409",	"田辺留依");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 71,	"伊集院惠",				"いじゅういんめぐみ",	"Co",	"0924",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 72,	"氏家むつみ",			"うじいえむつみ",		"Co",	"0713",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 73,	"梅木音葉",				"うめきおとは",			"Co",	"0620",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 74,	"大石泉",				"おおいしいずみ",		"Co",	"1111",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 75,	"岡崎泰葉",				"おかざきやすは",		"Co",	"0716",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 76,	"上条春菜",				"かみじょうはるな",		"Co",	"0410",	"長島光那");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 77,	"神谷奈緒",				"かみやなお",			"Co",	"0916",	"松井恵理子");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 78,	"川島瑞樹",				"かわしまみずき",		"Co",	"1125",	"東山奈央");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 79,	"神崎蘭子",				"かんざきらんこ",		"Co",	"0408",	"内田真礼");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 80,	"岸部彩華",				"きしべあやか",			"Co",	"1113",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 81,	"木場真奈美",			"きばまなみ",			"Co",	"0808",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 82,	"桐野アヤ",				"きりのあや",			"Co",	"0408",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 83,	"桐生つかさ",			"きりゅうつかさ",		"Co",	"0224",	"河瀬茉希");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 84,	"黒川千秋",				"くろかわちあき",		"Co",	"0226",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 85,	"ケイト",				"けいと",				"Co",	"0815",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 86,	"小室千奈美",			"こむろちなみ",			"Co",	"0609",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 87,	"鷺沢文香",				"さぎさわふみか",		"Co",	"1027",	"M・A・O");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 88,	"佐々木千枝",			"ささきちえ",			"Co",	"0607",	"今井麻夏");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 89,	"佐城雪美",				"さじょうゆきみ",		"Co",	"0928",	"中澤ミナ");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 90,	"塩見周子",				"しおみしゅうこ",		"Co",	"1212",	"ルゥ ティン");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 91,	"篠原礼",				"しのはられい",			"Co",	"1122",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 92,	"渋谷凛",				"しぶやりん",			"Co",	"0810",	"福原綾香");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 93,	"白坂小梅",				"しらさかこうめ",		"Co",	"0328",	"桜咲千依");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 94,	"砂塚あきら",			"すなづかあきら",		"Co",	"1007",	"富田美憂");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 95,	"瀬名詩織",				"せなしおり",			"Co",	"0110",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 96,	"高垣楓",				"たかがきかえで",		"Co",	"0614",	"早見沙織");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 97,	"高橋礼子",				"たかはしれいこ",		"Co",	"0508",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 98,	"鷹富士茄子",			"たかふじかこ",			"Co",	"0101",	"森下来奈");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values( 99,	"高峯のあ",				"たかみねのあ",			"Co",	"0325",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(100,	"多田李衣菜",			"ただりいな",			"Co",	"0630",	"青木瑠璃子");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(101,	"橘ありす",				"たちばなありす",		"Co",	"0731",	"佐藤亜美菜");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(102,	"東郷あい",				"とうごうあい",			"Co",	"0207",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(103,	"成宮由愛",				"なるみやゆめ",			"Co",	"1103",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(104,	"西川保奈美",			"にしかわほなみ",		"Co",	"1023",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(105,	"新田美波",				"にったみなみ",			"Co",	"0727",	"洲崎綾");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(106,	"二宮飛鳥",				"にのみやあすか",		"Co",	"0203",	"青木志貴");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(107,	"服部瞳子",				"はっとりとうこ",		"Co",	"1011",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(108,	"速水奏",				"はやみかなで",			"Co",	"0701",	"飯田友子");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(109,	"柊志乃",				"ひいらぎしの",			"Co",	"1225",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(110,	"久川颯",				"ひさかわはやて",		"Co",	"0616",	"長江里加");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(111,	"藤居朋",				"ふじいとも",			"Co",	"0701",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(112,	"藤原肇",				"ふじわらはじめ",		"Co",	"0615",	"鈴木みのり");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(113,	"古澤頼子",				"ふるさわよりこ",		"Co",	"0518",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(114,	"ヘレン",				"へれん",				"Co",	"0404",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(115,	"北条加蓮",				"ほうじょうかれん",		"Co",	"0905",	"渕上舞");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(116,	"松尾千鶴",				"まつおちづる",			"Co",	"0321",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(117,	"松永涼",				"まつながりょう",		"Co",	"1001",	"千菅春香");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(118,	"松本沙理奈",			"まつもとさりな",		"Co",	"0901",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(119,	"水木聖來",				"みずきせいら",			"Co",	"0427",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(120,	"水野翠",				"みずのみどり",			"Co",	"1205",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(121,	"三船美優",				"みふねみゆ",			"Co",	"0225",	"原田彩楓");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(122,	"望月聖",				"もちづきひじり",		"Co",	"1225",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(123,	"森久保乃々",			"もりくぼのの",			"Co",	"0827",	"高橋花林");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(124,	"八神マキノ",			"やがみまきの",			"Co",	"1107",	"二ノ宮ゆい");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(125,	"大和亜季",				"やまとあき",			"Co",	"1216",	"村中知");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(126,	"結城晴",				"ゆうきはる",			"Co",	"0717",	"小市眞琴");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(127,	"吉岡沙紀",				"よしおかさき",			"Co",	"0508",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(128,	"ライラ",				"らいら",				"Co",	"0521",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(129,	"脇山珠美",				"わきやまたまみ",		"Co",	"0920",	"嘉山未紗");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(130,	"和久井留美",			"わくいるみ",			"Co",	"0407",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(131,	"愛野渚",				"あいのなぎさ",			"Pa",	"0801",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(132,	"相葉夕美",				"あいばゆみ",			"Pa",	"0415",	"木村珠莉");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(133,	"赤城みりあ",			"あかぎみりあ",			"Pa",	"0414",	"黒沢ともよ");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(134,	"イヴ・サンタクロース",	"いぶさんたくろうす",	"Pa",	"1224",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(135,	"市原仁奈",				"いちはらにな",			"Pa",	"0208",	"久野美咲");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(136,	"上田鈴帆",				"うえだすずほ",			"Pa",	"1026",	"春野ななみ");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(137,	"衛藤美紗希",			"えとうみさき",			"Pa",	"0318",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(138,	"海老原菜帆",			"えびはらなほ",			"Pa",	"0803",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(139,	"及川雫",				"おいかわしずく",		"Pa",	"0603",	"のぐちゆり");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(140,	"大槻唯",				"おおつきゆい",			"Pa",	"0507",	"山下七海");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(141,	"片桐早苗",				"かたぎりさなえ",		"Pa",	"0307",	"和氣あず未");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(142,	"北川真尋",				"きたがわまひろ",		"Pa",	"0217",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(143,	"喜多日菜子",			"きたひなこ",			"Pa",	"0406",	"深川芹亜");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(144,	"喜多見柚",				"きたみゆず",			"Pa",	"1202",	"武田羅梨沙多胡");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(145,	"木村夏樹",				"きむらなつき",			"Pa",	"0819",	"安野希世乃");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(146,	"キャシー・グラハム",	"きゃしいぐらはむ",		"Pa",	"0919",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(147,	"小関麗奈",				"こせきれいな",			"Pa",	"0305",	"長野佑紀");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(148,	"小松伊吹",				"こまついぶき",			"Pa",	"1117",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(149,	"財前時子",				"ざいぜんときこ",		"Pa",	"0418",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(150,	"斉藤洋子",				"さいとうようこ",		"Pa",	"1229",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(151,	"冴島清美",				"さえじまきよみ",		"Pa",	"0926",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(152,	"佐藤心",				"さとうしん",			"Pa",	"0722",	"花守ゆみり");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(153,	"沢田麻理菜",			"さわだまりな",			"Pa",	"0506",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(154,	"首藤葵",				"しゅとうあおい",		"Pa",	"0818",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(155,	"城ヶ崎美嘉",			"じょうがさきみか",		"Pa",	"1112",	"佳村はるか");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(156,	"城ヶ崎莉嘉",			"じょうがさきりか",		"Pa",	"0730",	"山本希望");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(157,	"杉坂海",				"すぎさかうみ",			"Pa",	"0720",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(158,	"仙崎恵磨",				"せんざきえま",			"Pa",	"0627",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(159,	"相馬夏美",				"そうまなつみ",			"Pa",	"0723",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(160,	"高森藍子",				"たかもりあいこ",		"Pa",	"0725",	"金子有希");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(161,	"土屋亜子",				"つちやあこ",			"Pa",	"0502",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(162,	"十時愛梨",				"とときあいり",			"Pa",	"1208",	"原田ひとみ");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(163,	"ナターリア",			"なたありあ",			"Pa",	"0629",	"生田輝");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(164,	"並木芽衣子",			"なみきめいこ",			"Pa",	"1014",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(165,	"南条光",				"なんじょうひかる",		"Pa",	"0913",	"神谷早矢佳");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(166,	"難波笑美",				"なんばえみ",			"Pa",	"0501",	"伊達朱里紗");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(167,	"西島櫂",				"にしじまかい",			"Pa",	"0817",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(168,	"野々村そら",			"ののむらそら",			"Pa",	"0103",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(169,	"浜川愛結奈",			"はまかわあゆな",		"Pa",	"0525",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(170,	"浜口あやめ",			"はまぐちあやめ",		"Pa",	"0113",	"田澤茉純");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(171,	"久川凪",				"ひさかわなぎ",			"Pa",	"0616",	"立花日菜");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(172,	"日野茜",				"ひのあかね",			"Pa",	"0804",	"赤﨑千夏");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(173,	"姫川友紀",				"ひめかわゆき",			"Pa",	"0914",	"杜野まこ");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(174,	"星輝子",				"ほししょうこ",			"Pa",	"0606",	"松田颯水");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(175,	"堀裕子",				"ほりゆうこ",			"Pa",	"0313",	"鈴木絵理");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(176,	"本田未央",				"ほんだみお",			"Pa",	"1201",	"原紗友里");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(177,	"槙原志保",				"まきはらしほ",			"Pa",	"0427",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(178,	"松山久美子",			"まつやまくみこ",		"Pa",	"0121",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(179,	"的場梨沙",				"まとばりさ",			"Pa",	"1119",	"集貝はな");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(180,	"真鍋いつき",			"まなべいつき",			"Pa",	"1229",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(181,	"三好紗南",				"みよしさな",			"Pa",	"0625",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(182,	"向井拓海",				"むかいたくみ",			"Pa",	"0807",	"原優子");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(183,	"村上巴",				"むらかみともえ",		"Pa",	"0103",	"花井美春");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(184,	"メアリー・コクラン",	"めありいこくらん",		"Pa",	"0119",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(185,	"諸星きらり",			"もろぼしきらり",		"Pa",	"0901",	"松嵜麗");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(186,	"矢口美羽",				"やぐちみう",			"Pa",	"0710",	null);
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(187,	"夢見りあむ",			"ゆめみりあむ",			"Pa",	"0912",	"星希成奏");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(188,	"依田芳乃",				"よりたよしの",			"Pa",	"0703",	"高田憂希");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(189,	"龍崎薫",				"りゅうざきかおる",		"Pa",	"0720",	"春瀬なつみ");
insert into cinderella.idols(`id`, `name`, `kana`, `type`, `birth`, `cv`) values(190,	"若林智香",				"わかばやしともか",		"Pa",	"0830",	null);
